### PR TITLE
Make better dashboard for influenza estimator.

### PR DESCRIPTION
**Pull request by Hephaestus12**

### CODE REVIEW

**Comment by geektoni** [comment]
There is something wrong with this PR. Some of the commits here are from the old PR. I think you need to rebase against shogun-toolbox/applications's master branch to push only the commits you need.

**Comment by Hephaestus12** [comment]
I've rebased and pushed. But there is still a lot of files to be able to review thisi PR. I'll suggest you clone this branch and try running the code :)

**Comment by geektoni** [comment]
> I've rebased and pushed. But there is still a lot of files to be able to review thisi PR. I'll suggest you clone this branch and try running the code :)

mmh there are still commits which shouldn't be there. As you can see, most of the commits come from your fist PR. I can try it locally, but we won't be able to merge this PR as it is now.

**Comment by Hephaestus12** [comment]
Closing PR as opened another to deal with the git merge issues :)

**Pull request closed without merging**
